export { embedText, embedTexts } from './embeddings'
export { chunkText } from './chunker'
export { storeEmbeddings, searchSimilar, deleteEmbeddings } from './store'
export type { EmbeddingRow, SearchResult, SearchOpts } from './store'
export type { EscopoRAG, TipoConhecimento } from './types'
export { TIPOS_GLOBAIS, TIPOS_CLIENTE } from './types'
